"""Configuration package for LLMployable"""

from .config import (
    Config,
    DevelopmentConfig,
    StagingConfig,
    ProductionConfig,
    TestingConfig,
    get_config,
    config,
    Environment,
)
from .exceptions import (
    LLMployableException,
    ValidationError,
    InvalidGitHubUsername,
    InvalidJobDescription,
    ExternalServiceError,
    GitHubAPIError,
    GitHubUserNotFound,
    GitHubRateLimitExceeded,
    GeminiAPIError,
    GeminiQuotaExceeded,
    LinkedInError,
    ProcessingError,
    JobAnalysisError,
    ResumeGenerationError,
    LaTeXCompilationError,
    ConfigurationError,
    MissingAPIKey,
    RateLimitError,
    CacheError,
    DatabaseError,
    DatabaseConnectionError,
)
from .logging_config import (
    setup_logging,
    get_logger,
    app_logger,
    api_logger,
    error_logger,
)

__all__ = [
    # Config
    "Config",
    "DevelopmentConfig",
    "StagingConfig",
    "ProductionConfig",
    "TestingConfig",
    "get_config",
    "config",
    "Environment",
    # Exceptions
    "LLMployableException",
    "ValidationError",
    "InvalidGitHubUsername",
    "InvalidJobDescription",
    "ExternalServiceError",
    "GitHubAPIError",
    "GitHubUserNotFound",
    "GitHubRateLimitExceeded",
    "GeminiAPIError",
    "GeminiQuotaExceeded",
    "LinkedInError",
    "ProcessingError",
    "JobAnalysisError",
    "ResumeGenerationError",
    "LaTeXCompilationError",
    "ConfigurationError",
    "MissingAPIKey",
    "RateLimitError",
    "CacheError",
    "DatabaseError",
    "DatabaseConnectionError",
    # Logging
    "setup_logging",
    "get_logger",
    "app_logger",
    "api_logger",
    "error_logger",
]
